# Generated by Django 3.2.18 on 2023-03-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='gift_balance',
            field=models.PositiveBigIntegerField(),
        ),
    ]
