# Generated by Django 3.2.18 on 2023-03-26 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20230324_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertmodels',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='money.account'),
        ),
        migrations.AlterField(
            model_name='transfertmodels',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='money.account'),
        ),
    ]
